### ISSUE TITLE
Remove travis config

### ISSUE THREAD

**Issue by webignition** [webignition/basil-cli-compiler#209]
Previous travis config:

```yaml
language: php
php:
  - '7.4'

services:
  - docker

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci
  - composer phar-build
  - composer phar-test
  - ./build/ci.sh

cache:
  directories:
  - "$HOME/.composer/cache/files"

deploy:
  - provider: releases
    api_key:
      secure: ~redacted~
    file: build/compiler.phar
    on:
      tags: true
    skip_cleanup: 'true'

  - provider: script
    script: ./deploy/docker_hub_push.sh
    on:
      tags: true
    skip_cleanup: 'true'

  - provider: script
    script: ./deploy/docker_hub_push.sh
    on:
      branch: "master"
    skip_cleanup: 'true'

```
