### ISSUE TITLE
Examine github actions context when handling a tagged release

### ISSUE THREAD

**Issue by webignition** [webignition/basil-cli-compiler#224]
```yaml
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "The event name is ${{ github.event_name }}"
          echo "$GITHUB_CONTEXT"
```
